apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: votesystem-db
  namespace: prod-db
spec:
  crVersion: 1.19.1
  secretsName: mysql-secrets
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: disabled
  unsafeFlags:
    tls: true
    pxcSize: false
    proxySize: true
  tls:
    enabled: false
  pxc:
    size: 3                     
    image: percona/percona-xtradb-cluster:8.0.32-24.2
    configuration: |
      [mysqld]
      performance_schema=off
      innodb_buffer_pool_size=64M
    resources:
      requests:
        cpu: "200m"
        memory: "400Mi"
      limits:
        cpu: "600m"
        memory: "700Mi"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi

  haproxy:
    enabled: true
    size: 2
    image: percona/haproxy:2.8.17
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    readinessProbes:
      initialDelaySeconds: 30    # HAProxy necesita que PXC esté Ready primero
      timeoutSeconds: 5
      periodSeconds: 5
      failureThreshold: 10