apiVersion: v1
kind: Service
metadata:
  name: votesystem-db
  namespace: default
  labels:
    app: votesystem-db
spec:
  type: ExternalName
  externalName: votesystem-db-haproxy.prod-db.svc.cluster.local
