apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: prod-db
type: Opaque
stringData:
  root: votepassword
  xtrabackup: votepassword
  monitor: votepassword
  clusterhash: votepassword
  proxyadmin: votepassword